import scrapy
from scrapy.item import Item, Field

class OtodomItem(scrapy.Item):
    link = Field()
    cena = Field()
    cena_za_metr_kw = Field()
    lokalizacja = Field()
    liczba_pokoi = Field()
    metraz = Field()
    ogrzewanie = Field()
    pietro = Field()
    czynsz = Field()
    stan_wykonczenia = Field()
    rynek = Field()
    rodzaj_zabudowy = Field()
    liczba_pieter = Field()
    dwupoziomowe = Field()
    forma_wlasnosci = Field()
    dostepne_od = Field()
    typ_ogloszeniodawcy = Field()
    informacje_dodatkowe = Field()
    obsluga_zdalna = Field()
    garaz = Field()
    miejsce_parkingowe = Field()
    ogrodek = Field()
    taras = Field()
    rok_budowy = Field()
    winda = Field()
    material_budynku = Field()
    okna = Field()
    certyfikat_energetyczny = Field()
    wyposazenie = Field()
    zabezpieczenia = Field()
    media = Field()
    zdjecia = Field()
